###create a new user:
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "firstName": "Karl",
  "lastName": "Karlson",
  "phone": "054",
  "email": "karl@mail.com",
  "password": "Karl123!",
  "dob": "2002-01-26"
}

###sign a user in:
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "email": "mike10@lee.com",
  "password": "Password!1"
}

###get all posts:
GET http://localhost:8080/api/v1/packages
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsaXNhQG1haWwuY29tIiwiaWF0IjoxNjk0NjI0NDQ1LCJleHAiOjE2OTcyMTY0NDV9.9r640oxe8LI9zT-8VsMho1bgbE8XP_AESKsGYAxhtUHoP0Th2jptzf9wnlNvc4qPDMpIjSYYGcjUlCZentWL6g

###get all posts:
GET http://localhost:8080/api/v1/packages
Authorization: Basic lisa@mail.com Lisa123!

###delete a user:
DELETE http://localhost:8080/api/v1/auth/356
Authorization: Basic admin@admin.com Admin!123