###create a new package:
POST http://localhost:8080/api/v1/packages
Content-Type: application/json

{
  "title": "Greenland",
  "destination": "Nuuk",
  "description": "Nordic Trip",
  "content": "Cold, Very Cold",
  "price": 1299,
  "availableDate": "2024-03-15"
}

###get all packages:
GET http://localhost:8080/api/v1/packages

###find package by destination:
GET http://localhost:8080/api/v1/packages/q?destination=Nuuk

###get package by id:
GET http://localhost:8080/api/v1/packages/1

###update a post:
PUT http://localhost:8080/api/v1/packages/1952
Content-Type: application/json

{
  "title": "Greenland",
  "destination": "Nuuk",
  "description": "Steep mountains, deep fjords and giant icebergs",
  "content": "Greenland is an island autonomous territory of Denmark in North America. It lies between the Arctic and Atlantic oceans, east of the Canadian Arctic...",
  "price": 4099,
  "availableDate": "2024-03-10"
}

###delete package by id
DELETE http://localhost:8080/api/v1/packages/1102
